# frozen_string_literal: true

source "https://rubygems.org"
git_source(:github) { |repo| 'https://github.com/#{repo}.git' }

ruby "2.6.4"

gem "dotenv-rails", groups: [:development, :test]

gem "rails", "~> 6.0.0"
gem "mysql2", ">= 0.4.4"
gem "puma", "~> 3.11"
gem "bootsnap", ">= 1.4.2", require: false

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible
gem "rack-cors"

# 位置情報を扱うため
gem "geocoder"

# JSONの返却にSerializerを使う
gem "active_model_serializers", "~> 0.10.0"

# JSON Web Tokenを扱うためにimport
gem "jwt"
gem "aws-sdk-cognitoidentityprovider"

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  # pry-byebugを用いるためコメントアウト
  # gem "byebug", platforms: [:mri, :mingw, :x64_mingw]
  gem "rspec-rails", "~> 3.8"
  gem "pry-rails"
  gem "pry-byebug"
  gem "pry-doc"
end

group :development do
  gem "rubocop-rails", require: false
  gem "rubocop-performance", require: false
  gem "listen", ">= 3.0.5", "< 3.2"
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem "spring"
  gem "spring-watcher-listen", "~> 2.0.0"
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: [:mingw, :mswin, :x64_mingw, :jruby]
