# Railsコンテナ用Dockerfile

# イメージのベースラインにRuby2.6.4を指定
FROM ruby:2.6.4-alpine
# Railsに必要なパッケージをインストール
RUN apk update && \
    apk add --update nodejs nodejs-npm && \
    apk add --no-cache bash tzdata libxml2-dev curl-dev make gcc libc-dev g++ mariadb-dev mysql-client vim
# ルートディレクトリを作成
RUN mkdir /app
# 作業ディレクトリを指定
WORKDIR /app

# ローカルのGemfileとGemfile.lock、bundleをコピー
COPY ./api/src/Gemfile ./Gemfile
COPY ./api/src/Gemfile.lock ./Gemfile.lock

# Gemのインストール実行
RUN gem install bundler --no-document && \
    bundle install && \
    rm -rf /usr/local/bundle/cache/* /usr/local/share/.cache/* /var/cache/* /tmp/*
# apk del libxml2-dev curl-dev make gcc libc-dev g++

# ローカルのsrcをコピー
COPY ./api/src /app

# Start the main process.
# CMD ["rails", "server", "-b", "0.0.0.0"]
CMD ["rails", "db:setup", "RAILS_ENV=production"]
CMD ["rails", "server", "-b", "0.0.0.0", "RAILS_ENV=production"]